{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "authz-listeners.fullname" . }}
  labels:
    {{- include "authz-listeners.labels" . | nindent 4 }}
type: Opaque
data:
  AUTHZED_TOKEN: {{ .Values.secrets.authzedToken | b64enc | quote }}
  RABBIT_URI: {{ .Values.secrets.rabbitUri | b64enc | quote }}
{{- end }}
